
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import type { Metadata } from "next";
import AuthContext from "@/libs/auth-context";
import LoginModal from "@/components/modals/login-modal";
import RegisterModal from "@/components/modals/registar-modal";


export const metadata: Metadata = {
  title: "ScholarPal",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <LoginModal />
          <RegisterModal />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
