
import "./globals.css";
import type { Metadata } from "next";

import AuthContext from "@/libs/auth-context";

import LoginModal from "@/components/modals/login-modal";
import RegisterModal from "@/components/modals/registar-modal";
import AIModal from "@/components/modals/ai-modal";
import NewPostModal from "@/components/modals/new-post-modal";
import EditModal from "@/components/modals/edit-modal";
import CreateGroupModal from "@/components/modals/create-group-modal";
import NotificationDisplayModal from "@/components/modals/notification-display-modal";
import UserCardModal from "@/components/modals/user-cards-modal";
import GroupNewPostModal from "@/components/modals/group-new-post-modal";


export const metadata: Metadata = {
  title: "ScholarPal",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <LoginModal />
          <RegisterModal />
          <AIModal />
          <NewPostModal />
          <GroupNewPostModal />
          <EditModal />
          <CreateGroupModal />
          <NotificationDisplayModal />
          <UserCardModal />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
