
import "./globals.css";
import type { Metadata } from "next";

import AuthContext from "@/libs/auth-context";

import LoginModal from "@/components/modals/login-modal";
import RegisterModal from "@/components/modals/registar-modal";
import AIModal from "@/components/modals/ai-modal";
import NewPostModal from "@/components/modals/new-post-modal";


export const metadata: Metadata = {
  title: "ScholarPal",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <LoginModal />
          <RegisterModal />
          <AIModal />
          <NewPostModal />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
